--- 
- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка web серверов
  hosts: webserver
  roles:
    - role: webserver
  tags:
    - webserver 

- name: Установка и настройка Load Balancer
  hosts: loadbalancer
  roles:
    - role: load_balancer
  tags:
    - loadbalancer
